### ISSUE TITLE
Mobile Menu

### ISSUE THREAD

**Issue by holly-johnson** [haylikent/cc-website#25]
- It could be a bit taller - it should optically appear the same size as your button if not the same exactly. 

- The top box shadow should be removed. The shadow doesn't go well with your brand.

**Comment by holly-johnson** [comment]
On mobile this definitely needs fixed because the shadow shouldn't be at top. If you leave it for desktop at all you need to tone it way down.

**Comment by haylikent** [comment]
I have brought down the shadow a ton, it is super faint--I only have this on there because I am worried that with the top bar being the same as the background then the sticky nav will get lost at certain points when scrolling. I took it off for small display
