### ISSUE TITLE
Page Headings

### ISSUE THREAD

**Issue by holly-johnson** [haylikent/cc-website#28]
The H1 style on every page is much more elegant and strong. Also making it even more slim.  
![Screen Shot 2020-03-26 at 9 45 49 PM](https://user-images.githubusercontent.com/15253544/77716051-3a835e00-6fab-11ea-9f9a-cb6351c6e9fd.png)

**Comment by haylikent** [comment]
I made the secondary headers less heavy at the top by manually adjusting the grid container padding that was on it-- I did this to all the secondary pages
