### ISSUE TITLE
Contact Page spacing

### ISSUE THREAD

**Issue by holly-johnson** [haylikent/cc-website#30]
On mobile: 
doesn't seem to be a space between submit and office hours. 
the indent of the hours looks accidental. I would just keep it left aligned like everything else.

On desktop:
remove the indents here as well. lower to large-4 and add a large-offset-1. Need a much larger gutter
![Screen Shot 2020-03-26 at 9 54 23 PM](https://user-images.githubusercontent.com/15253544/77716570-7bc83d80-6fac-11ea-979c-855e350aefc1.png)

**Comment by haylikent** [comment]
is the large-offset a SCSS property? I am only seeing it listed under sass in the foundation.zurb documents

**Comment by haylikent** [comment]
Disregard the earlier comment! I found what you were talking about and implemented that on the contact page
